#!/bin/bash

export PATH=$PATH:$(pwd)

source cv_env/bin/activate

INSTALL_FLAG=-i

if [[ $# > 1 || ($# == 1 && $1 != $INSTALL_FLAG) ]]
then
	echo "Usage: $(basename $0) [ <$INSTALL_FLAG> ]"
	exit 1
fi

if [[ $1 == $INSTALL_FLAG ]]; then
	pip install -r requirements.txt
fi

