VERSION = 'SELECT version()'
CREATE_TABLE = \
"""
CREATE TABLE models (
    ID SERIAL PRIMARY KEY,
    GENERATOR BYTEA NOT NULL,
    DISCRIMINATOR BYTEA NOT NULL
);
"""

INSERT_MODEL = 'INSERT INTO models (GENERATOR, DISCRIMINATOR) VALUES (%s, %s)'

SELECT_MODEL = 'SELECT GENERATOR, DISCRIMINATOR FROM models WHERE ID = %s'